version: '3'
services:
  db:
    image: mariadb:10.5
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '13306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=example
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
volumes:
  db_data:
